### PR TITLE
Replace "Connection refused" by ConnectException

### PR DESCRIPTION
**Pull request by julianladisch**
"Connection refused" is a locale dependent String; the unit test
fails under other locales like German.

Replace by checking the Exception class.

### CODE REVIEW

**Review by adamdickmeiss — APPROVED** [review]
This worries me a bit, as I thought using getMessage rather than getLocalizedMessage everywhere would solve this. Can  you, for example, run all Okapi tests?

**Review by hjiebsco — APPROVED** [review]

**Comment by julianladisch** [comment]
The existing code uses getMessage() rather than getLocalizedMessage(), Netty generates the German translation that getMessage() returns.

I've already fixed the Okapi tests:
https://github.com/folio-org/okapi/commit/35c42b1b1bf74429bd5b508a558113d2f3d07655
https://github.com/folio-org/okapi/commit/e645af97b04564104b5b54c166134a36d794b4b0

**Comment by adamdickmeiss** [comment]
> The existing code uses getMessage() rather than getLocalizedMessage(), Netty generates the German translation that getMessage() returns.
> 
> I've already fixed the Okapi tests:
> [folio-org/okapi@35c42b1](https://github.com/folio-org/okapi/commit/35c42b1b1bf74429bd5b508a558113d2f3d07655)
> [folio-org/okapi@e645af9](https://github.com/folio-org/okapi/commit/e645af97b04564104b5b54c166134a36d794b4b0)

Thx. One is missing -- which you didn't see because that will not run on Windows.

**Comment by adamdickmeiss** [comment]
> > The existing code uses getMessage() rather than getLocalizedMessage(), Netty generates the German translation that getMessage() returns.
> > I've already fixed the Okapi tests:
> > [folio-org/okapi@35c42b1](https://github.com/folio-org/okapi/commit/35c42b1b1bf74429bd5b508a558113d2f3d07655)
> > [folio-org/okapi@e645af9](https://github.com/folio-org/okapi/commit/e645af97b04564104b5b54c166134a36d794b4b0)
> 
> Thx. One is missing -- which you didn't see because that will not run on Windows.

(This was a red herring, as this was returned by Docker itself).

Anyway this PR is approved.

**Pull request merged**
