### PR TITLE
RMB-854: Increase FORM_ATTRIBUTE_SIZE_MAX from 16384 to 32768

### PR DESCRIPTION
**Pull request by julianladisch**
Some tenants exceed the current limit of 16384.

Solution: Double the limit.

### CODE REVIEW

**Review by hjiebsco — APPROVED** [review]
Can we go higher (10x or 5x) to be safe?

**Review by adamdickmeiss — APPROVED** [review]

**Comment by julianladisch** [comment]
> Can we go higher (10x or 5x) to be safe?

This limit exists for security reasons and should be as small as possible.

Can you report what your tenants need?

For a clean solution we were making this configurable so that only mod-login-saml uses 32768 and all other modules use the default 2048.

**Comment by hjiebsco** [comment]
> > Can we go higher (10x or 5x) to be safe?
> 
> This limit exists for security reasons and should be as small as possible.
> 
> Can you report what your tenants need?
> 
> For a clean solution we were making this configurable so that only mod-login-saml uses 32768 and all other modules use the default 2048.

The case I encountered was just over 16K. I have no objection to 32K.

**Review by steveellis — APPROVED** [review]
Doubling it seems fine since it seems like we know already that 16 may not be enough, especially if we're doing other validation besides size.

**Pull request merged**
