### PR TITLE
Removed transaction created during stream get

### PR DESCRIPTION
**Pull request by wwelling**

### CODE REVIEW

**Comment by skoczko** [comment]
@julianladisch I am a little confused by this, I thought the JDBC driver was used only for migrations?

**Comment by wwelling** [comment]
@skoczko the driver change had no effect. Don't see an issue with it being upgraded though. Will remove from this PR.

**Comment by julianladisch** [comment]
Is there a reproducer - a test that fails with the old code and succeeds with the new code?

**Comment by wwelling** [comment]
No, there is not a test that reproduces the problem. This issue only began occurring for Q2 deployment attempts. 

https://issues.folio.org/browse/MODUSERS-213

The existing tests do still pass. Is there a reason for this method always starting a transaction?

**Comment by wwelling** [comment]
https://vertx.io/docs/vertx-pg-client/java/#_cursors_and_streaming

// Cursors require to run within a transaction
    Transaction tx = connection.begin();

I am going to attempt to write a test to cause the same failure as we have when deploying Q2.

**Comment by wwelling** [comment]
Closing for further investigation.

**Pull request closed without merging**
