### PR TITLE
RMB-650: Client generator support Date query parameter

### PR DESCRIPTION
**Pull request by wwelling**

### CODE REVIEW

**Comment by wwelling** [comment]
@julianladisch do you have any ideas how to go about testing this?

**Comment by julianladisch** [comment]
You can extract the code block of `if (AnnotationGrabber.QUERY_PARAM.equals(paramType))` into a method.
You can remove `private` from all methods you want to test. If the unit test class is in the org/folio/rest/tools package it can access the method.

**Comment by wwelling** [comment]
@julianladisch I understand that much. What about assertions? How do we know these methods ran as expected.

**Comment by wwelling** [comment]
I will be trying to write unit tests. Other than that would like feedback as to approach.

**Comment by julianladisch** [comment]
Closed in favour of #711 (code + tests).

**Pull request closed without merging**
