### PR TITLE
Dot not apply ower for full text queries RMB-455

### PR DESCRIPTION
**Pull request by adamdickmeiss**

### CODE REVIEW

**Comment by julianladisch** [comment]
This is already fixed in the pull request https://github.com/folio-org/raml-module-builder/pull/489 " RMB-432: RMB-438: fulltext: word splitting, punctuation, minus" that explicitely disables all lower() in queryByFt.

**Comment by julianladisch** [comment]
All changes this pull request makes will be overwritten by #489 .

**Comment by adamdickmeiss** [comment]
Closing as this code will  not be merged to master . Only part of b26.3 branch.

**Comment by julianladisch** [comment]
Commit in b26.3 branch: https://github.com/folio-org/raml-module-builder/commit/72b0b4274d7d61feec8ce0c40300605c054d483b

**Pull request closed without merging**
