### PR TITLE
RMB-602: PostgresClient.delete futurisation

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Review by adamdickmeiss — APPROVED** [review]

**Review by hjiebsco — APPROVED** [review]
Is `deleteByPojo` used by any module?

**Comment by julianladisch** [comment]
deleteByPojo is not used by any module published on https://github.com/search?q=org%3Afolio-org+deletebypojo

**Comment by hjiebsco** [comment]
> deleteByPojo is not used by any module published on https://github.com/search?q=org%3Afolio-org+deletebypojo

I mean the delete by entity methods like Line 1588, 1597, and 1606 in PostgresClient.

**Comment by julianladisch** [comment]
I don't know.
You may use some java IDE, open all modules you want to search in, open PostgresClient.java, click on any of the delete(String, Object, Handler) and delete(AsyncResult, String, Object, Handler) methods and search for references.

**Pull request merged**
